stages:
- stage: Approval
  displayName: Approve the release
  jobs:
  - deployment: ApproveRelease
    displayName: "Approve Release"
    environment: "makecode" # Defined in AzDO Pipeline environments
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none