stages:
- stage: Approval
  displayName: Approve the release
  dependsOn: Build
  jobs:
  - job: ApproveRelease
    displayName: "Approve Release"
    pool: server
    timeoutInMinutes: 120
    steps:
      - task: ManualValidation@0
        inputs:
          notifyUsers: ''
          instructions: 'Please approve the release before continuing'
          onTimeout: 'reject'
