parameters:
  - name: isPreRelease
    type: boolean

steps:
- checkout: self

- task: NodeTool@0
  displayName: Install Node.js
  inputs:
    versionSpec: 16.x

- bash: |
    echo "Compiling Production Webpack"
    yarn && yarn package-web
    echo "Compiled Production Webpack"
  displayName: Compile

- ${{ if eq(parameters.isPreRelease, true) }}:
  - script: npx @vscode/vsce package --pre-release
    displayName: Package pre-release extension VSIX

- ${{ if eq(parameters.isPreRelease, false) }}:
  - script: npx @vscode/vsce package
    displayName: Package extension VSIX

- publish: pxt-vscode-web.vsix 
  artifact: pxt-vscode-web.vsix 
  displayName: Publish VSIX artifact