parameters:
  - name: isPreRelease
    type: boolean

steps:
- checkout: self

- task: NodeTool@0
  displayName: Install Node.js
  inputs:
    versionSpec: 16.x

# Create a unique filename for the extension vsix to match the verison number
- bash: |
    VSIX=$(node -p "require(\"./package.json\").publisher + \".\" + require(\"./package.json\").name + \".\" + require(\"./package.json\").version + \".vsix\"")
    echo "##vso[task.setvariable variable=VSIX;isOutput=true]$VSIX"
  name: SetExtensionName
  displayName: Set VSIX file name


# Yarn package script to build the vsix file
- bash: |
    echo "Compiling Production Webpack"
    yarn && yarn package-web
    echo "Compiled Production Webpack"
  displayName: Compile

- ${{ if parameters.isPreRelease }}:
  - script: npx @vscode/vsce package -o $(Build.ArtifactStagingDirectory)/$(SetExtensionName.VSIX) --pre-release
    displayName: Package pre-release extension VSIX

- ${{ else }}:
  - script: npx @vscode/vsce package -o $(Build.ArtifactStagingDirectory)/$(SetExtensionName.VSIX)
    displayName: Package extension VSIX

- publish: $(Build.ArtifactStagingDirectory)/$(SetExtensionName.VSIX) 
  artifact: $(SetExtensionName.VSIX) 
  displayName: Publish VSIX artifact
