# Shared stages template for release and pre-release pipelines
parameters:
- name: nodeVersion
  type: string
  default: '20.x'
- name: isPreRelease
  type: boolean
- name: signType
  type: string

stages:
  # Stage to build the VSIX and publish it
- template: build.yml
  parameters:
    isPreRelease: ${{ parameters.isPreRelease }}
    nodeVersion: ${{ parameters.nodeVersion }}
    signType: ${{ parameters.signType }}

# Stage provides a manual approval step before the publish stage is run
- template: approval.yml

# Publish the VSIX to the extension marketplace
- template: publish.yml
  parameters:
    isPreRelease: ${{ parameters.isPreRelease }}
    nodeVersion: ${{ parameters.nodeVersion }}
