parameters:
  - name: isPreRelease
    type: boolean

stages:
- stage: Publish
  displayName: Publish the VSIX
  dependsOn:
    - Build
    - Approval
  jobs:
  - job: Publish
    variables:
    - name: vsixName
      value: $[ stageDependencies.Build.Build.outputs['SetExtensionName.VSIX'] ]
    steps:
    - download: current
      artifact: extension
      displayName: 🚚 Download extension artifact

    - download: current
      artifact: extension-manifest
      displayName: 🚚 Download extension manifest artifact

    - download: current
      artifact: extension-signature
      displayName: 🚚 Download extension signature artifact


    - ${{ if parameters.isPreRelease }}:
      - bash: echo "Publishing PreRelease"
      - script: npx @vscode/vsce@latest publish --packagePath $(Pipeline.Workspace)/extension/$(vsixName) --manifestPath $(Pipeline.Workspace)/extension-manifest/$(vsixName).manifest --signaturePath $(Pipeline.Workspace)/extension-signature/$(vsixName).signature.p7s --pre-release
        displayName: Publish pre-release extension
        env:
          # Marketplace PAT needs to be uploaded as a pipeline variable
          VSCE_PAT: $(marketplace-pat)

    - ${{ else }}:
      - bash: echo "Publishing Release"
      - script: npx @vscode/vsce@latest publish --packagePath $(Pipeline.Workspace)/extension/$(vsixName) --manifestPath $(Pipeline.Workspace)/extension-manifest/$(vsixName).manifest --signaturePath $(Pipeline.Workspace)/extension-signature/$(vsixName).signature.p7s
        displayName: Publish extension
        env:
          VSCE_PAT: $(marketplace-pat)
