name: pxt-buildmain

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    name: buildmain

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: '16.x'
      - name: yarn install
        uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1.12.1
        with:
          install-command: yarn install
      - name: Linting
        run: yarn lint
      - name: Compiling
        run: yarn compile-web
      - name: Testing
        run: xvfb-run -a yarn test
      - name: Production webpack
        run: yarn package-web
      - name: Build vsix
        run: npx -p=vsce vsce package --yarn --out vscode-makecode-arcade.vsix
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: extension
          path: vscode-makecode-arcade.vsix
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: vscode-makecode-arcade.vsix