name: pxt-buildpr

on: [pull_request]

jobs:
  build:
    name: buildpr

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - name: Linting
        run: npm run lint
      - name: Compiling
        run: npm run compile-web
      - name: Testing
        run: xvfb-run -a npm run test