name: pxt-buildpr

on: [pull_request]

jobs:
  build:
    name: buildpr

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '16.x'
      - name: yarn install
        uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1.12.1
        with:
          install-command: yarn install
      - name: Linting
        run: yarn lint
      - name: Compiling
        run: yarn compile-web
      - name: Testing
        run: xvfb-run -a yarn test