name: pxt-buildmain

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    name: buildmain

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: yarn install
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn install
      - name: Linting
        run: yarn lint
      - name: Compiling
        run: yarn compile-web
      - name: Testing
        run: xvfb-run -a yarn test
      - name: Production webpack
        run: yarn package-web
      - name: Build vsix
        run: npx -p=vsce vsce package --yarn --out vscode-makecode-arcade.vsix
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: vscode-makecode-arcade.vsix
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: vscode-makecode-arcade.vsix